spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sol_financ
    password: p@$$w0rd
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
   port: 8081
   error:
     include-stacktrace: never

security:
  jwt:
    token:
      secret-key: p@$$w0rdp@$$w0rd
      expire-length: 300000
      
UsuarioController:
  signin: Autenticar usuário e retornar token JWT.
  signup: Criar usuário e retornar token JWT.
  delete: Delete um usuário específico.
  search: Retorna um usuário específico.
  me: Retorna usuário logado.
  refresh: Re-autenticar usuário e retornar token JWT.